test_hw: null  # Hardware identifier for the test (change this to your specific storage hardware, like "RPi_4B_USB_flash_drive")
test_data_sizes_mB: [10, 100]  # Data sizes to benchmark in MB (e.g., 10 MB, 100 MB, 1 GB)
num_runs: 1  # Number of runs to perform for each test
